/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ifspsaocarlos.gastock.views.desktop;

import br.com.ifspsaocarlos.gastock.controllers.Combustivel;
import br.com.ifspsaocarlos.gastock.controllers.Frentista;
import br.com.ifspsaocarlos.gastock.controllers.Gerente;
import javax.swing.JOptionPane;

/**
 *
 * @author Alex
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form sistema
     */
    
    
    public Login() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        labelData = new javax.swing.JLabel();
        labelMensagem = new javax.swing.JLabel();
        labelHora = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        textSenha = new javax.swing.JPasswordField();
        imagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Autenticação - Gastock");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(49, 49, 49));
        setMaximumSize(new java.awt.Dimension(500, 400));
        setMinimumSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 400));
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        btnEntrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEntrar);
        btnEntrar.setBounds(30, 320, 120, 40);

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair);
        btnSair.setBounds(350, 320, 120, 40);

        jLabel1.setText("Unidade: São Carlos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(250, 120, 230, 16);

        labelDia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelDia.setForeground(new java.awt.Color(255, 0, 0));
        labelDia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDia.setText("Segunda-Feira");
        labelDia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelDia);
        labelDia.setBounds(340, 290, 140, 15);

        labelData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelData.setForeground(new java.awt.Color(255, 0, 0));
        labelData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelData.setText("04/05/2017");
        labelData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelData);
        labelData.setBounds(340, 270, 140, 20);

        labelMensagem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelMensagem.setForeground(new java.awt.Color(255, 0, 0));
        labelMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMensagem.setText("Bom dia!");
        labelMensagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelMensagem);
        labelMensagem.setBounds(340, 210, 140, 20);

        labelHora.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelHora.setForeground(new java.awt.Color(255, 0, 0));
        labelHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHora.setText("22:56:14");
        labelHora.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelHora);
        labelHora.setBounds(340, 230, 140, 20);

        labelLogin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(255, 255, 255));
        labelLogin.setText("Login");
        getContentPane().add(labelLogin);
        labelLogin.setBounds(30, 190, 60, 22);

        textLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLoginActionPerformed(evt);
            }
        });
        getContentPane().add(textLogin);
        textLogin.setBounds(30, 210, 300, 30);

        labelSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelSenha.setForeground(new java.awt.Color(255, 255, 255));
        labelSenha.setText("Senha");
        getContentPane().add(labelSenha);
        labelSenha.setBounds(30, 250, 100, 22);

        textSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textSenhaFocusGained(evt);
            }
        });
        getContentPane().add(textSenha);
        textSenha.setBounds(30, 270, 300, 30);

        imagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifspsaocarlos/gastock/images/fundo.png"))); // NOI18N
        getContentPane().add(imagemFundo);
        imagemFundo.setBounds(0, 0, 500, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {                                         

        Frentista[] f = new Frentista[3];
        f[0] = new Frentista("Geraldo","1234",1000.01f);
        f[1] = new Frentista("Agnalda","1234",2000.01f);
        f[2] = new Frentista("Robertina","1234",2000.01f);
        
        Gerente[] g = new Gerente[1];
        g[0] = new Gerente();
        g[0].setNome("admin");
        g[0].setSalario(9999.99f);
        g[0].setSenha("admin");
        
        Gerente user = null;
        
        for (Gerente ger : g){
            if (textLogin.getText().equals(ger.getNome()) && textSenha.getText().equals(ger.getSenha())) {
           
                JOptionPane.showMessageDialog(null, "Bem vindo");
                
                // Inicio teste
                
//                Combustivel c = new Combustivel();
//                c.setCombustivelId(1);    
//                c.setNome("Gasolina teste");
//                c.setPreco(3.85);
//                        
//                CombustivelJDialog dialog = new CombustivelJDialog(null);
//                dialog.setCombustivel(c); 
//                dialog.setVisible(true);
//                dialog.dispose();
//                
//                
//               
//                Combustivel c1 = dialog.getCombustivel();
//                System.out.println("Nome:" +c1.getNome() );
//                //System.out.println("Id:"+combustivel1.getCombustivelId() );
//                System.out.println("Preço:" +c1.getPreco() );
//                
//                dialog = null;
//                
                //fim teste
                user = ger;
            }
        }
        if (user == null)
             JOptionPane.showMessageDialog(null, "Acesso Negado");
    }
    private void textLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLoginActionPerformed

    private void textSenhaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textSenhaFocusGained
        textSenha.setText("");
    }//GEN-LAST:event_textSenhaFocusGained

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel imagemFundo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelData;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelHora;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelMensagem;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JTextField textLogin;
    private javax.swing.JPasswordField textSenha;
    // End of variables declaration//GEN-END:variables
}
